#include "music.h"

volatile unsigned int sound_enabled = 0;
volatile unsigned int current_note = G4;
volatile unsigned int ms_elapsed = 0;

static unsigned int ms_per_tick = 0;

void set_bpm(unsigned int bpm) {
    ms_per_tick = 60000 / (TICKS_PER_BEAT * bpm);
}

void play(unsigned int note, unsigned int duration_ticks) {
    unsigned int duration_ms = 0;
    duration_ms = duration_ticks * ms_per_tick;
    current_note = note;
    sound_enabled = 1;
    ms_elapsed = 0;
    while (ms_elapsed < duration_ms - DEAD_TIME_MS);
    sound_enabled = 0;
    while (ms_elapsed < duration_ms);
}

void song_play() {
    set_bpm(150);
    play(G3, 1);
    play(E4, 1);
    play(G4, 1);
    play(A4, 1);
    play(F4, 1);
    play(G4, 1);
    play(E4, 1);
    play(C4, 1);
    play(D4, 1);
    play(B3, 1);
    play(G4, 1);
    play(Fs4, 1);
    play(F4,1);
    play(Ds4, 1);
    play(E4, 1);
    play(G4, 1);
    play(Fs4, 1);
    play(F4,1);
    play(Ds4, 1);
    play(E4, 1);
    play(C5, 1);
    play(C5, 1);
    play(C5, 1);
    play(G3, 1);
    play(E4, 1);
    play(G4, 1);
    play(A4, 1);
    play(F4, 1);
    play(G4, 1);
    play(E4, 1);
    play(C4, 1);

    set_bpm(180);
    play(A5, 4);
    play(A3, 4);
    play(A5, 4);
    play(A3, 4);
    play(A5, 4);
    play(Fs5, 4);
    play(E5, 4);
    play(Ds5, 4);
    play(D5, 2);
    play(G3, 2);
    play(B3, 2);
    play(G3, 2);
    play(D5, 2);
    play(G3, 2);
    play(B3, 2);
    play(G3, 2);
    play(D5, 2);
    play(G3, 2);
    play(B3, 2);
    play(G4, 1);
    play(B4, 1);
    play(D5, 2);
    play(G3, 2);
    play(E5, 2);
    play(G3, 2);
    play(D5, 2);
    play(Fs3, 2);
    play(A3, 2);
    play(A4, 2);
    play(Fs5, 2);
    play(Fs3, 2);
    play(A5, 2);
    play(Fs3, 2);
    play(Gs5, 2);
    play(Fs3, 2);
    play(A5, 2);
    play(Fs3, 2);
    play(Gs5, 1);
    play(A5, 1);
    play(Gs5, 1);
    play(Fs5, 1);
    play(D5, 2);
    play(A4, 2);
    play(B4, 2);
    play(G3, 1);
    play(Cs5, 1);
    play(D5, 2);
    play(G3, 1);
    play(E5, 1);
    play(Fs5, 1);
    play(F5, 1);
    play(Fs5, 1);
    play(G5, 1);
    play(A5, 1);
    play(G5, 1);
    play(Fs5, 1);
    play(E5, 1);
    play(D5, 1);
    play(Cs5, 1);
    play(D5, 1);
    play(A5, 1);
    play(Cs5, 1);
    play(C5, 1);
    play(Cs5, 1);
    play(A5, 1);
    play(Cs5, 1);
    play(C5, 1);
    play(B4, 1);
    play(Bb4, 1);
    play(A4, 1);
    play(Gs4, 1);
    play(G4, 1);
    play(E4, 1);
    play(A4, 2);
    play(A3, 2);
    play(D4, 2);
    play(A3, 2);
    play(B4, 2);
    play(A3, 2);
    play(A4, 2);
    play(A3, 2);
    play(D4, 2);
    play(D5, 2);
    play(Cs5, 2);
    play(D5, 2);
    play(Fs5, 2);
    play(A3, 2);
    play(E5, 2);
    play(D5, 2);
    play(B4, 2);
    play(G3, 2); 
    play(B4, 2);
    play(G3, 2);
    play(E5, 2);
    play(G3, 2);
    play(D5, 2);
    play(G3, 2);
    play(B4, 2);
    play(B4, 2);
    play(Bb4, 2);
    play(B4, 2);
    play(D5, 2);
    play(G3, 2);
    play(Cs5, 2);
    play(B4, 2);
    play(A4, 2);
    play(Fs3, 2);
    play(Fs3, 2);
    play(A4, 2);
    play(Fs3, 2);
    play(Fs3, 2);
    play(A5, 2);
    play(Fs3, 2);
}
